// 2. 用于校验的数据
interface CheckData {
    cId: number;
    type: number; // 0老旧核心 1镀层部件 2先祖遗产 3蜡烛 4序列号
    nm: string; // 场景名称
    ev: string; // 证据
    vd: string; // 视频坐标
}

export const checkDataList: CheckData[] = [
    // 老旧核心
    {cId:1, type: 0, nm: "地基数删入口", ev:"CARCASS:Carcass_security_glide_P1", vd: "p=146"},
    {cId:2, type: 0, nm: "都市地下左侧", ev:"CARCASS:Carcass_LQ_under_hub_P4", vd: "p=147"},
    {cId:3, type: 0, nm: "地基数删出口", ev:"CARCASS:Carcass_security_glide_P3", vd: "p=148"},
    {cId:4, type: 0, nm: "地基电梯中段豁口", ev:"CARCASS:Carcass_trois_mouches", vd: "p=149"},
    {cId:5, type: 0, nm: "“血”门口台阶隐藏", ev:"CARCASS:Carcass_LQ_city_lobby_secret", vd: "p=150"},
    {cId:6, type: 0, nm: "地球末裔左下", ev:"CARCASS:Carcass_LQ_city_lobby_C2", vd: "p=151"},
    {cId:7, type: 0, nm: "地基入口与庞西亚对话", ev:"DIALOG:TXT_LQ_CITY_FOUNDATIONS", vd: "p=152"},
    {cId:8, type: 0, nm: "地基回血房间左侧房", ev:"CARCASS:Carcass_LQ_under_chall_C3", vd: "p=153"},
    {cId:9, type: 0, nm: "地基回血点大房间右上", ev:"CARCASS:Carcass_LQ_under_chall_P3", vd: "p=154"},
    {cId:10, type: 0, nm: "地基拿完神行步后", ev:"CARCASS:Carcass_LQ_under_tuto_C2", vd: "p=155"},
    {cId:11, type: 0, nm: "打完母贝雕刻师直走", ev:"CARCASS:Carcass_LQ_ruins_intro_S1", vd: "p=156"},
    {cId:12, type: 0, nm: "居所滑雪", ev:"CARCASS:Carcass_LQ_ruins_intro_C2", vd: "p=157"},
    {cId:13, type: 0, nm: "鸟笼中花坛下冲", ev:"CARCASS:Carcass_GA_bou_crop_P2", vd: "p=158"},
    {cId:14, type: 0, nm: "天空舱上方通道", ev:"CARCASS:Carcass_TW_mid_data_S1", vd: "p=159"},
    {cId:15, type: 0, nm: "天空舱传送点右", ev:"CARCASS:Carcass_TW_common_right", vd: "p=160"},
    {cId:16, type: 0, nm: "钟塔通路电梯左侧门顶", ev:"CARCASS:Carcass_GA_bou_up_F1", vd: "p=161"},
    {cId:17, type: 0, nm: "野生灌丛中部", ev:"CARCASS:Carcass_GA_root_center_P1", vd: "p=162"},
    {cId:18, type: 0, nm: "钟摆观景台电梯右", ev:"CARCASS:Carcass_GA_bou_build_F4", vd: "p=163"},
    {cId:19, type: 0, nm: "安港（“息”左侧树叶下冲）", ev:"CARCASS:Carcass_GA_bou_chill_S1", vd: "p=164"},
    {cId:20, type: 0, nm: "安港（钟塔之底）", ev:"CARCASS:Carcass_GA_bou_intro_F6", vd: "p=165"},
    {cId:21, type: 0, nm: "野生灌丛和阿周那对话", ev:"DIALOG:TXT_GA_ROOT_WRONGTURN", vd: "p=166"},
    {cId:22, type: 0, nm: "“息”左侧", ev:"CARCASS:Carcass_GA_bou_door_C1", vd: "p=167"},
    {cId:23, type: 0, nm: "安港和欧兰忒对话", ev:"DIALOG:TXT_GA_BOU_MINDYOURSTEP", vd: "p=168"},
    {cId:24, type: 0, nm: "野生灌丛右侧台阶内", ev:"CARCASS:Carcass_GA_root_conex_P1", vd: "p=169"},
    {cId:25, type: 0, nm: "“息”头顶", ev:"CARCASS:Carcass_GA_roof_leaves_C2", vd: "p=170"},
    {cId:26, type: 0, nm: "“息”下方", ev:"CARCASS:Carcass_GA_bou_glide_P2", vd: "p=171"},
    {cId:27, type: 0, nm: "穹传送点旁", ev:"CARCASS:Carcass_GA_vin_dusk_S1", vd: "p=172"},
    {cId:28, type: 0, nm: "穹下方雕像旁", ev:"CARCASS:Carcass_GA_roof_lakedark", vd: "p=173"},
    {cId:29, type: 0, nm: "“息”右下", ev:"CARCASS:Carcass_GA_vin_bridge_S1", vd: "p=174"},
    {cId:30, type: 0, nm: "步道与哈帕贡对话", ev:"DIALOG:TXT_GA_VIN_SUDDEN_PEARL", vd: "p=175"},
    {cId:31, type: 0, nm: "步道“朋友”上方", ev:"CARCASS:Carcass_GA_vin_aromatic_4", vd: "p=176"},
    {cId:32, type: 0, nm: "“血”身后", ev:"CARCASS:Carcass_GA_vin_hall_S2", vd: "p=177"},
    {cId:33, type: 0, nm: "宁静避所上方大厅", ev:"CARCASS:Carcass_ST_tube_top", vd: "p=178"},
    {cId:34, type: 0, nm: "储藏库传送点左", ev:"CARCASS:Carcass_ST_tube_hub_P2", vd: "p=179"},
    {cId:35, type: 0, nm: "宁静避所右边管道下去", ev:"CARCASS:Carcass_ST_tube_liquids_C4", vd: "p=180"},
    {cId:36, type: 0, nm: "深渊传送点左走到顶", ev:"CARCASS:Carcass_ST_pearl_lab_S1", vd: "p=181"},
    {cId:37, type: 0, nm: "深渊传送点右（环境有黏膜）", ev:"CARCASS:Carcass_ST_pearl_lab_sommet", vd: "p=182"},
    {cId:38, type: 0, nm: "深渊传送点下方（周围有水）", ev:"CARCASS:Carcass_ST_pearl_lab_P7", vd: "p=183"},
    {cId:39, type: 0, nm: "深渊传送点下方的下方", ev:"CARCASS:Carcass_ST_pearl_lab_P3", vd: "p=184"},
    // 镀层部件
    {cId: 1, type: 1, nm: "市政厅跳跳乐起点", ev: "SHIELD_FRAGMENT:20", vd: "p=128"},
    {cId: 2, type: 1, nm: "居所滑雪的镀层部件", ev: "SHIELD_FRAGMENT:14", vd: "p=129"},
    {cId: 3, type: 1, nm: "“脊”左侧需闪避的房间，遭遇战后从容器获取", ev: "SHIELD_FRAGMENT:18", vd: "p=130"},
    {cId: 4, type: 1, nm: "希伊托举右侧", ev: "SHIELD_FRAGMENT:19", vd: "p=131"},
    {cId: 5, type: 1, nm: "野生灌丛中部机器人残骸", ev: "SHIELD_FRAGMENT:10", vd: "p=132"},
    {cId: 6, type: 1, nm: "安港回血点上方（需弹弓）", ev: "SHIELD_FRAGMENT:16", vd: "p=133"},
    {cId: 7, type: 1, nm: "钟塔滑翔能力下方", ev: "SHIELD_FRAGMENT:6", vd: "p=134"},
    {cId: 8, type: 1, nm: "安港钟塔传送点右侧", ev: "SHIELD_FRAGMENT:7", vd: "p=135"},
    {cId: 9, type: 1, nm: "安港钟塔大厅", ev: "SHIELD_FRAGMENT:12", vd: "p=136"},
    {cId: 10, type: 1, nm: "野生灌丛勾锚点", ev: "SHIELD_FRAGMENT:11", vd: "p=137"},
    {cId: 11, type: 1, nm: "野生灌丛右上角", ev: "SHIELD_FRAGMENT:21", vd: "p=138"},
    {cId: 12, type: 1, nm: "“息”右下", ev: "SHIELD_FRAGMENT:22", vd: "p=139"},
    {cId: 13, type: 1, nm: "“血”身后", ev: "SHIELD_FRAGMENT:9", vd: "p=140"},
    {cId: 14, type: 1, nm: "制造场走管道", ev: "SHIELD_FRAGMENT:8", vd: "p=141"},
    {cId: 15, type: 1, nm: "精炼坊右上抽屉", ev: "SHIELD_FRAGMENT:23", vd: "p=142"},
    {cId: 16, type: 1, nm: "水滴跳跳乐入口", ev: "SHIELD_FRAGMENT:15", vd: "p=143"},
    {cId: 17, type: 1, nm: "“再见”追逐战路上", ev: "SHIELD_FRAGMENT:13", vd: "p=144"},
    {cId: 18, type: 1, nm: "深渊传送点上方", ev: "SHIELD_FRAGMENT:17", vd: "p=145"},
    {cId: 19, type: 1, nm: "梅尔购买1", ev: "SHIELD_FRAGMENT:0", vd: ""},
    {cId: 20, type: 1, nm: "梅尔购买2", ev: "SHIELD_FRAGMENT:1", vd: ""},
    {cId: 21, type: 1, nm: "梅尔购买3", ev: "SHIELD_FRAGMENT:2", vd: ""},
    {cId: 22, type: 1, nm: "梅尔购买4", ev: "SHIELD_FRAGMENT:3", vd: ""},
    {cId: 23, type: 1, nm: "梅尔购买5", ev: "SHIELD_FRAGMENT:4", vd: ""},
    {cId: 24, type: 1, nm: "梅尔购买6", ev: "SHIELD_FRAGMENT:5", vd: ""},
    // 先祖遗产
    {cId: 1, type: 2, nm: "居所滑雪场（伊赛）", ev: "ATTACK_POWER:0", vd: "p=2"},
    {cId: 2, type: 2, nm: "“脊”上方房间（格尔）", ev: "ATTACK_POWER:1", vd: "p=3"},
    {cId: 3, type: 2, nm: "“血”头顶（娜芙）", ev: "ATTACK_POWER:3", vd: "p=4"},
    {cId: 4, type: 2, nm: "“息”右侧（皮普）", ev: "ATTACK_POWER:2", vd: "p=5"},
    {cId: 5, type: 2, nm: "深渊右侧（阿露）", ev: "ATTACK_POWER:4", vd: "p=6"},
    // 蜡烛
    {cId: 1, type: 3, nm: "都市谐调室与埃尔辛对话", ev: "CANDLE:8", vd: "p=33"},
    {cId: 2, type: 3, nm: "安港遭遇战后开箱", ev: "CANDLE:0", vd: "p=34"},
    {cId: 3, type: 3, nm: "钟塔传送点左", ev: "CANDLE:1", vd: "p=35"},
    {cId: 4, type: 3, nm: "波尔特门身后", ev: "CANDLE:11", vd: "p=36"},
    {cId: 5, type: 3, nm: "数删传送点右", ev: "CANDLE:10", vd: "p=37"},
    {cId: 6, type: 3, nm: "“手”左边", ev: "CANDLE:9", vd: "p=38"},
    {cId: 7, type: 3, nm: "安港（需神行步）", ev: "CANDLE:7", vd: "p=39"},
    {cId: 8, type: 3, nm: "宁静避所下方", ev: "CANDLE:5", vd: "p=40"},
    {cId: 9, type: 3, nm: "“洗衣机”旁", ev: "CANDLE:3", vd: "p=41"},
    {cId: 10, type: 3, nm: "“息”门口", ev: "CANDLE:6", vd: "p=42"},
    {cId: 11, type: 3, nm: "都市左侧", ev: "CANDLE:2", vd: "p=43"},
    {cId: 12, type: 3, nm: "地基最底层", ev: "CANDLE:4", vd: "p=44"},
    // 序列号
    {cId: 1, type: 4, nm: "地基数删传送点下方", ev: "CHEST_KEY:5", vd: "p=45"},
    {cId: 2, type: 4, nm: "地基数删最下方", ev: "CHEST_KEY:3", vd: "p=46"},
    {cId: 3, type: 4, nm: "地基数删下方通道", ev: "CHEST_KEY:2", vd: "p=47"},
    {cId: 4, type: 4, nm: "步道数删传送点左", ev: "CHEST_KEY:0", vd: "p=48"},
    {cId: 5, type: 4, nm: "步道数删左下", ev: "CHEST_KEY:4", vd: "p=49"},
    {cId: 6, type: 4, nm: "步道数删右侧", ev: "CHEST_KEY:1", vd: "p=50"},
]