// 2. 用于校验的数据
interface CheckData {
    checkId: number;
    type: number; // 0面具,1丝轴,3盒子,4金属,5苔梅,6跳蚤
    scene: string; // 场景名称
    evi: number; // 证据来源 0场景 1购买 2任务
    evidence1: string; // 用以确认的证据
    evidence2: string; // 用以确认的证据
    axis: string; // 场景坐标(没有就写任务或商店)
}

export const checkDataList: CheckData[] = [
    {checkId: 1, type: 4, scene: "骸骨洞窟", evi: 0, evidence1: "Bone_07", evidence2: "Collectable Item Pickup - Tool Metal", axis: "Bone_07(37,5)"},
    {checkId: 2, type: 4, scene: "深坞右侧宝箱", evi: 0, evidence1: "Dock_03", evidence2: "Collectable Item Pickup", axis: "Dock_03(11,82)"},
    {checkId: 3, type: 3, scene: "猎人小径野兽教堂旁", evi: 0, evidence1: "Ant_20", evidence2: "Collectable Item Pickup", axis: "Ant_20(145,12)"},
    {checkId: 4, type: 0, scene: "远野炸地板", evi: 0, evidence1: "Bone_East_20", evidence2: "Heart Piece", axis: "Bone_East_20(92,17)"},
    {checkId: 5, type: 0, scene: "骸底买面具", evi: 1, evidence1: "Bonetown", evidence2: "1", axis: "商店购买"},
    {checkId: 6, type: 4, scene: "骸底买金属", evi: 1, evidence1: "Bonetown", evidence2: "2", axis: "商店购买"},
    {checkId: 7, type: 0, scene: "沙虫道_简易钥匙门前（底部隐藏墙）", evi: 0, evidence1: "Crawl_02", evidence2: "Heart Piece", axis: "Crawl_02(22,5)"},
    {checkId: 8, type: 3, scene: "朝圣者憩所购买", evi: 1, evidence1: "Bone_East_10_Room", evidence2: "3", axis: "商店购买"},
    {checkId: 9, type: 0, scene: "甲木林（下劈花朵连跳）", evi: 0, evidence1: "Shellwood_14", evidence2: "Heart Piece", axis: "Shellwood_14(128,12)"},
    {checkId: 10, type: 3, scene: "骸骨洞窟(需螳螂爪)", evi: 0, evidence1: "Bone_18", evidence2: "Collectable Item Pickup", axis: "Bone_18(36,22)"},
    {checkId: 11, type: 0, scene: "洞窟与深坞之间", evi: 0, evidence1: "Dock_08", evidence2: "Heart Piece", axis: "Dock_08(54,20)"},
    {checkId: 12, type: 3, scene: "骸底提交暴烈燧甲虫任务", evi: 2, evidence1: "Bonetown", evidence2: "Rock Rollers", axis: "任务提交"},
    {checkId: 13, type: 1, scene: "出生点织巢", evi: 0, evidence1: "Weave_11", evidence2: "Silk Spool", axis: "Weave_11(15,24)"},
    {checkId: 14, type: 3, scene: "钟心镇购买盒子", evi: 1, evidence1: "Belltown", evidence2: "4", axis: "商店购买"},
    {checkId: 15, type: 3, scene: "工厂忏悔机旁光源（打完白愈厅boss向下）", evi: 0, evidence1: "Under_08", evidence2: "Collectable Item Pickup", axis: "Under_08(61,18)"},
    {checkId: 16, type: 1, scene: "圣煲工厂", evi: 0, evidence1: "Under_10", evidence2: "Silk Spool", axis: "Under_10(22,6)"},
    {checkId: 17, type: 1, scene: "圣扉巨门顶部", evi: 0, evidence1: "Song_19_entrance", evidence2: "Silk Spool", axis: "Song_19_entrance(22,94)"},
    {checkId: 18, type: 3, scene: "圣煲钟道顶部", evi: 0, evidence1: "Bellway_City", evidence2: "Collectable Item Pickup", axis: "Bellway_City(68,26)"},
    {checkId: 19, type: 1, scene: "圣煲工厂底部", evi: 0, evidence1: "Library_11b", evidence2: "Silk Spool", axis: "Library_11b(22,7)"},
    {checkId: 20, type: 4, scene: "圣煲工厂", evi: 0, evidence1: "Under_19b", evidence2: "Collectable Item Pickup - Tool Metal", axis: "Under_19b(10,7)"},
    {checkId: 21, type: 1, scene: "灰沼顶部", evi: 0, evidence1: "Greymoor_02", evidence2: "Silk Spool", axis: "Greymoor_02(30,137)"},
    {checkId: 22, type: 1, scene: '白愈厅救谢尔玛', evi: 0, evidence1: "Ward_09", evidence2: "ward_junk_pile_break", axis: "商店购买"},
    {checkId: 23, type: 1, scene: '白愈厅电梯下方', evi: 0, evidence1: "Ward_01", evidence2: "Silk Spool", axis: 'Ward_01(29,6)'},
    {checkId: 24, type: 1, scene: '钟心镇买丝轴', evi: 1, evidence1: "Belltown", evidence2: "5", axis: "商店购买"},
    {checkId: 25, type: 0, scene: '圣歌盟地买面具', evi: 1, evidence1: "Song_Enclave", evidence2: "6", axis: "商店购买"},
    {checkId: 26, type: 0, scene: '火灵竹林_最右侧', evi: 0, evidence1: "Wisp_07", evidence2: "Heart Piece", axis: 'Wisp_07(251,24)'},
    {checkId: 27, type: 4, scene: '火灵竹林_上方小道旁', evi: 0, evidence1: "Wisp_05", evidence2: "Collectable Item Pickup - Tool Metal", axis: 'Wisp_05(42,58)'},
    {checkId: 28, type: 1, scene: '忆廊_左侧翠庭生态区', evi: 0, evidence1: "Arborium_09", evidence2: "Silk Spool", axis: 'Arborium_09(19,32)'},
    {checkId: 29, type: 3, scene: '忆廊_中部甲木林生态区', evi: 0, evidence1: "Arborium_05", evidence2: "Collectable Item Pickup", axis: 'Arborium_05(5,9)'},
    {checkId: 30, type: 4, scene: '腐殖渠', evi: 0, evidence1: "Aqueduct_05", evidence2: "Collectable Item Pickup - Tool Metal", axis: 'Aqueduct_05(325,17)'},
    {checkId: 31, type: 0, scene: '远野岩浆挑战', evi: 0, evidence1: "Bone_East_LavaChallenge", evidence2: "Heart Piece (1)", axis: 'Bone_East_LavaChallenge(21,278)'},
    {checkId: 32, type: 3, scene: '腐汁泽左上角', evi: 0, evidence1: "Shadow_20", evidence2: "Collectable Item Pickup", axis: 'Shadow_20(18,25)'},
    {checkId: 33, type: 3, scene: '腐汁泽打沙包', evi: 0, evidence1: "Shadow_27", evidence2: "Sack Corpse Pickup", axis: 'Shadow_27(192,10)'},
    {checkId: 34, type: 0, scene: '腐汁泽（粪海狂蛆跑酷）', evi: 0, evidence1: "Shadow_13", evidence2: "Heart Piece", axis: 'Shadow_13(308,63)'},
    {checkId: 35, type: 3, scene: '中途酒馆', evi: 0, evidence1: "Halfway_01", evidence2: "Collectable Item Pickup", axis: 'Halfway_01(9,15)'},
    {checkId: 36, type: 1, scene: '蚀阶小偷购买', evi: 1, evidence1: "Coral_42", evidence2: "7", axis: "商店购买"},
    {checkId: 37, type: 3, scene: '卡拉卡沙川', evi: 0, evidence1: "Coral_23", evidence2: "Collectable Item Pickup", axis: 'Coral_23(91,52)'},
    {checkId: 38, type: 4, scene: '蚀阶（boss门前两铃铛下去）', evi: 0, evidence1: "Coral_32", evidence2: "Collectable Item Pickup - Tool Metal", axis: 'Coral_32(78,9)'},
    {checkId: 39, type: 1, scene: '解救14只跳蚤', evi: 1, evidence1: "Coral_Judge_Arena", evidence2: "8", axis: "任务提交"},
    {checkId: 40, type: 3, scene: '灰沼车站左侧', evi: 0, evidence1: "Greymoor_16", evidence2: "Collectable Item Pickup", axis: 'Greymoor_16(131,53)'},
    {checkId: 41, type: 0, scene: '机枢核心左边', evi: 0, evidence1: "Song_09", evidence2: "Heart Piece", axis: 'Song_09(42,43)'},
    {checkId: 42, type: 0, scene: '出生点织巢', evi: 0, evidence1: "Weave_05b", evidence2: "Heart Piece", axis: 'Weave_05b(161,29)'},
    {checkId: 43, type: 0, scene: '钟心镇猎杀兽蝇任务', evi: 2, evidence1: "Belltown", evidence2: "Beastfly Hunt", axis: "任务提交"},
    {checkId: 44, type: 0, scene: '图书馆玻璃罐', evi: 0, evidence1: "Library_05", evidence2: "library_glass_heart_piece", axis: 'Library_05(17,70)'},
    {checkId: 45, type: 1, scene: '高庭顶部', evi: 0, evidence1: "Hang_03_top", evidence2: "Silk Spool", axis: 'Hang_03_top(18,156)'},
    {checkId: 46, type: 4, scene: '圣歌盟地买金属（需再寻商贾）', evi: 1, evidence1: "Song_Enclave", evidence2: "9", axis: "商店购买"},
    {checkId: 47, type: 1, scene: '圣歌盟地买丝轴（需再寻商贾）', evi: 1, evidence1: "Song_Enclave", evidence2: "10", axis: "商店购买"},
    {checkId: 48, type: 0, scene: '罪石监狱上右', evi: 0, evidence1: "Slab_17", evidence2: "Heart Piece", axis: 'Slab_17(19,68)'},
    {checkId: 49, type: 1, scene: '罪石监狱左侧', evi: 0, evidence1: "Peak_01", evidence2: "Silk Spool", axis: 'Peak_01(86,192)'},
    {checkId: 50, type: 0, scene: '雪山柱子内', evi: 0, evidence1: "Peak_04c", evidence2: "Heart Piece", axis: 'Peak_04c(68,8)'},
    {checkId: 51, type: 0, scene: '蚀阶（冲刺跳+飞针+二段跳）', evi: 0, evidence1: "Coral_19b", evidence2: "Heart Piece", axis: 'Coral_19b(75,108)'},
    {checkId: 52, type: 1, scene: '深坞（熔岩地板房）', evi: 0, evidence1: "Bone_East_13", evidence2: "Silk Spool", axis: 'Bone_East_13(41,24)'},
    {checkId: 53, type: 1, scene: '德鲁伊下方', evi: 0, evidence1: "Bone_11b", evidence2: "Silk Spool", axis: 'Bone_11b(31,5)'},
    {checkId: 54, type: 1, scene: '深坞右侧', evi: 0, evidence1: "Dock_03c", evidence2: "Silk Spool", axis: 'Dock_03c(128,55)'},
    {checkId: 55, type: 1, scene: '机枢核心右下', evi: 0, evidence1: "Cog_07", evidence2: "Silk Spool", axis: 'Cog_07(83,15)'},
    {checkId: 56, type: 3, scene: '沙虫道左下', evi: 0, evidence1: "Crawl_09", evidence2: "Collectable Item Pickup", axis: 'Crawl_09(130,5)'},
    {checkId: 57, type: 3, scene: '蚀阶（下层椅子跳跳乐）', evi: 0, evidence1: "Coral_02", evidence2: "Collectable Item Pickup (1)", axis: 'Coral_02(202,45)'},
    {checkId: 58, type: 3, scene: '图书馆右上', evi: 0, evidence1: "Library_08", evidence2: "Collectable Item Pickup", axis: 'Library_08(106,35)'},
    {checkId: 59, type: 3, scene: '深坞温泉房下方', evi: 0, evidence1: "Dock_13", evidence2: "Collectable Item Pickup", axis: 'Dock_13(15,5)'},
    {checkId: 60, type: 3, scene: '罪石监狱', evi: 0, evidence1: "Slab_Cell_Quiet", evidence2: "Collectable Item Pickup", axis: 'Slab_Cell_Quiet(43,32)'},
    {checkId: 61, type: 3, scene: '第三幕远野右上方_女王门口右侧', evi: 0, evidence1: "Bone_East_25", evidence2: "Collectable Item Pickup", axis: 'Bone_East_25(152,8)'},
    {checkId: 62, type: 0, scene: '第三幕飞毛腿赛跑', evi: 2, evidence1: "Sprintmaster_Cave", evidence2: "Sprintmaster Race", axis: "Sprintmaster_Cave(50,14)"},
    {checkId: 63, type: 3, scene: '第三幕钟心镇上冲', evi: 0, evidence1: "Belltown", evidence2: "Collectable Item Pickup", axis: 'Belltown(59,68)'},
    {checkId: 64, type: 0, scene: '第三幕雪山洞窟', evi: 0, evidence1: "Peak_06", evidence2: "Heart Piece", axis: 'Peak_06(28,182)'},
    {checkId: 65, type: 0, scene: '第三幕暗蚀之心任务', evi: 2, evidence1: "Belltown", evidence2: "Destroy Thread Cores", axis: '任务提交'},
    {checkId: 66, type: 0, scene: '第三幕隐秘猎手任务', evi: 2, evidence1: "Belltown", evidence2: "Ant Trapper", axis: '任务提交'},
    {checkId: 67, type: 5, scene: '忆廊_椅子旁', evi: 0, evidence1: "Arborium_04", evidence2: "moss_berry_fruit", axis: 'Arborium_04(72,9)'},
    {checkId: 68, type: 5, scene: '苔穴出生点左上', evi: 0, evidence1: "Tut_02", evidence2: "moss_berry_fruit", axis: 'Tut_02(140,50)'},
    {checkId: 69, type: 5, scene: '出生点织巢左侧', evi: 0, evidence1: "Weave_03", evidence2: "moss_berry_fruit", axis: 'Weave_03(165,28)'},
    {checkId: 70, type: 5, scene: '苔穴出生点右上', evi: 0, evidence1: "Tut_01b", evidence2: "moss_berry_fruit", axis: 'Tut_01b(74,89)'},
    {checkId: 71, type: 5, scene: '骸底镇上空_蚊子', evi: 1, evidence1: 'Bonetown', evidence2: '11', axis: 'Bonetown(286,55)'},
    {checkId: 72, type: 5, scene: '德鲁伊下方_蚊子', evi: 1, evidence1: 'Bone_05b', evidence2: '12', axis: 'Bone_05b(61,25)'},
    {checkId: 73, type: 5, scene: '漫游者教堂上空_蚊子', evi: 1, evidence1: 'Bonegrave', evidence2: '13', axis: 'Bonegrave(253,39)'},
    {checkId: 74, type: 6, scene: '深坞_冲刺能力旁', evi: 1, evidence1: '_', evidence2: '14', axis: 'Bone_East_05(35,39)'},
    {checkId: 75, type: 6, scene: '深坞_车站隐藏墙', evi: 1, evidence1: '_', evidence2: '15', axis: 'Dock_16(52,21)'},
    {checkId: 76, type: 6, scene: '深坞右下方隐藏房（需飞针）', evi: 1, evidence1: '_', evidence2: '16', axis: 'Dock_03d(102,69)'},
    {checkId: 77, type: 6, scene: '远野左侧笼子', evi: 1, evidence1: '_', evidence2: '17', axis: 'Bone_East_17b(85,30)'},
    {checkId: 78, type: 6, scene: '朝圣者憩所右侧门内(需从远野车站隐藏通道进入)', evi: 1, evidence1: '_', evidence2: '18', axis: 'Bone_East_10_Church(182,24)'},
    {checkId: 79, type: 6, scene: '灰沼_腐囊虫庭附近', evi: 1, evidence1: '_', evidence2: '19', axis: 'Greymoor_15b(179,54)'},
    {checkId: 80, type: 6, scene: '灰沼塔顶', evi: 1, evidence1: '_', evidence2: '20', axis: 'Greymoor_06(26,140)'},
    {checkId: 81, type: 6, scene: '灰沼_中途酒馆上方隐藏墙【色跳蚤】', evi: 1, evidence1: '_', evidence2: '21', axis: 'Greymoor_24(73,13)'},
    {checkId: 82, type: 6, scene: '甲木林拿螳螂爪路上', evi: 1, evidence1: '_', evidence2: '22', axis: 'Shellwood_03(26,48)'},
    {checkId: 83, type: 6, scene: '钟心镇上方钟道顶部', evi: 1, evidence1: '_', evidence2: '23', axis: 'Belltown_04(11,89)'},
    {checkId: 84, type: 6, scene: '骸骨洞窟', evi: 1, evidence1: '_', evidence2: '24', axis: 'Bone_06(101,24)'},
    {checkId: 85, type: 6, scene: '猎人小径左侧（下劈红豆上去）', evi: 1, evidence1: '_', evidence2: '25', axis: 'Ant_03(42,70)'},
    {checkId: 86, type: 6, scene: '罪途左侧笼子', evi: 1, evidence1: '_', evidence2: '26', axis: 'Dust_12(30,4)'},
    {checkId: 87, type: 6, scene: '雪山跳蚤', evi: 1, evidence1: '_', evidence2: '27', axis: 'Peak_05c(248,113)'},
    {checkId: 88, type: 6, scene: '圣堡工厂下层（全是炸弹人的房间）', evi: 1, evidence1: '_', evidence2: '28', axis: 'Under_21(9,16)'},
    {checkId: 89, type: 6, scene: '圣堡工厂底部（火灵竹林出来）', evi: 1, evidence1: '_', evidence2: '29', axis: 'Under_23(20,24)'},
    {checkId: 90, type: 6, scene: '蚀阶_车站左侧房间顶部', evi: 1, evidence1: '_', evidence2: '30', axis: 'Coral_35(7,144)'},
    {checkId: 91, type: 6, scene: '蚀阶_去往椅子路上', evi: 1, evidence1: '_', evidence2: '31', axis: 'Coral_24(33,45)'},
    {checkId: 92, type: 6, scene: '沙虫道_门上方隐藏墙', evi: 1, evidence1: '_', evidence2: '32', axis: 'Crawl_06(70,20)'},
    {checkId: 93, type: 6, scene: '罪石监狱_小房间', evi: 1, evidence1: '_', evidence2: '33', axis: 'Slab_Cell(52,6)'},
    {checkId: 94, type: 6, scene: '罪石监狱_车站旁椅子上方', evi: 1, evidence1: '_', evidence2: '34', axis: 'Slab_06(85,28)'},
    {checkId: 95, type: 6, scene: '忆廊顶部【大跳蚤】', evi: 1, evidence1: '_', evidence2: '35', axis: 'Arborium_08(34,32)'},
    {checkId: 96, type: 6, scene: '腐殖渠【龙牙跳蚤，救出可解锁全部跳蚤位置】', evi: 1, evidence1: '_', evidence2: '36', axis: 'Bellway_Aqueduct(67,63)'},
    {checkId: 97, type: 6, scene: '腐汁泽隐藏椅子上方跳蚤', evi: 1, evidence1: '_', evidence2: '37', axis: 'Shadow_10(82,41)'},
    {checkId: 98, type: 6, scene: '腐汁泽下方隐藏墙', evi: 1, evidence1: '_', evidence2: '38', axis: 'Shadow_28(31,22)'},
    {checkId: 99, type: 6, scene: '废旧管风琴（打完boss左走）', evi: 1, evidence1: '_', evidence2: '39', axis: 'Dust_09(6,35)'},
    {checkId: 100, type: 6, scene: '圣咏殿跳蚤（从餐厅往左走）', evi: 1, evidence1: '_', evidence2: '40', axis: 'Song_14(62,7)'},
    {checkId: 101, type: 6, scene: '圣咏殿隐藏墙跳蚤（下方隐藏墙有风扇）', evi: 1, evidence1: '_', evidence2: '41', axis: 'Song_11(51,165)'},
    {checkId: 102, type: 6, scene: '圣歌盟地右侧（需从图书馆隐藏墙上去）', evi: 1, evidence1: '_', evidence2: '42', axis: 'Library_09(126,101)'},
    {checkId: 103, type: 6, scene: '图书馆推箱子', evi: 1, evidence1: '_', evidence2: '43', axis: 'Library_01(49,87)'},
]